# Generated by Django 4.1.5 on 2023-05-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_rating_value_rating_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrition',
            new_name='description',
        ),
    ]
