# Generated by Django 4.1.5 on 2023-05-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_descrition_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='descrition',
            new_name='description',
        ),
    ]
